### PR TITLE
Refs #7 - Fix JSONField with default values saved to  XML

### PR DESCRIPTION
**Pull request by avoinea**

### CODE REVIEW

**Comment by ale-rt** [comment]
> LGTM, however, I have doubts if doctests are still a recommended and approved approach in core.
> 

I am not a big supporter of doctests, but I do not see this as a blocker.

I am more curious about the issue this PR is trying to solve: do we have a link to a github issue somewhere?

I must admit I am a little bit surprised :) The code now is super robust and that's great, but
why
```
>>> JSONField().fromUnicode({'items': []})
```
should not raise, given it is not a unicode value?

and why:
```
JSONField().fromUnicode("{'items': []}")
```
should not raise, given it is not a valid json?

Also:
```
JSONField().fromUnicode("{'items': []}")
```
is not unicode in Python 2.7 :)

Understanding what is the problem behind this might be great becode the method looks now more solid.

**Comment by avoinea** [comment]
@ale-rt The issue is #7

**Comment by ale-rt** [comment]
Oh I see. So this is a workaround to cope with the fact that the json we store is not an actual json :)

**Comment by ale-rt** [comment]
@jenkins-plone-org please run jobs

**Comment by avoinea** [comment]
> ```
> >>> JSONField().fromUnicode({'items': []})
> ```
> 
> 
> should not raise, given it is not a unicode value?

Ok, I think it should raise after all if the value is not a string representation of the JSON. 

@jenkins-plone-org please run jobs

**Comment by avoinea** [comment]
@ale-rt I'm not sure why the tests are failing now, but it doesn't seem related.

**Comment by ale-rt** [comment]
I restarted manually the failing tests

**Comment by avoinea** [comment]
@ale-rt They seems to be ok now. Who is supposed to merge it?

**Comment by ale-rt** [comment]
You can do that :) Because it is approved but I am here and I save you some time 8)

**Comment by ale-rt** [comment]
@avoinea #7 can be closed right?

**Comment by avoinea** [comment]
Yes. Thank you!

**Pull request merged**
