### PR TITLE
Fix install_requires

### PR DESCRIPTION
**Pull request by gforcada**
There's no import/zcml dependency on plone.app.dexterity.

All other imports come from z3c.dependencychecker analysis.

### CODE REVIEW

**Comment by jensens** [comment]
Would be nice to have a note in CHANGES.rst

**Comment by gforcada** [comment]
Done! Thanks for reviewing.

**Comment by davisagli** [comment]
plone.schemaeditor and plone.supermodel are not actually hard dependencies. The modules that import them are only included in the zcml if the packages are present.

**Comment by gforcada** [comment]
Removed them on https://github.com/plone/plone.schema/commit/86a02e428191ac1c8a5391b66c3a72733c833140

**Pull request merged**
